/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Booking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angelique
 */
public class ShowT extends javax.swing.JFrame {

    /**
     * Creates new form ShowT
     */
    public ShowT() {
        initComponents();
       
    }
   
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtchooser = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcustname = new javax.swing.JTextField();
        txtmno = new javax.swing.JTextField();
        txtsource = new javax.swing.JComboBox<>();
        txtdestin = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        txttime = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txtdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Admin Panel");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Bus Ticket Data");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Add other Admin");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("logout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 387, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(228, 228, 228)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 80));

        Table1.setBackground(new java.awt.Color(204, 204, 255));
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Bus No", "Customer Name", "Source", "Destination", "Mobile", "Date", "Time", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 118, 590, 380));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));
        getContentPane().add(txtchooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 207, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setText("Customer Name");

        jLabel6.setText("Source");

        jLabel7.setText("Destination");

        jLabel8.setText("Mobile");

        jLabel9.setText("Date");

        txtmno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmnoActionPerformed(evt);
            }
        });

        txtsource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kigali", "Muahanga", "Ruhango", "Nyanza", "Huye" }));

        txtdestin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Huye", "Nyanza", "Ruhango", "Muhanga", "Kigali" }));

        jButton4.setText("Time");

        txttime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7h00", "8h00", "9h00", "10h00", "11h00" }));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Book Now");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(28, 28, 28)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4))))
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcustname, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtsource, 0, 257, Short.MAX_VALUE)
                                        .addComponent(txtmno, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtdestin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtcustname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtsource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdestin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton7)
                    .addComponent(jButton8)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, 370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     Connection con;
    PreparedStatement pst;
     PreparedStatement pst1;
    ResultSet rs;
    
    public void load()
    {
         try {
            // TODO add your handling code here:
            SimpleDateFormat Df= new SimpleDateFormat();
            String date=Df.format(txtchooser.getDate());
            Class.forName("com.mysql.jdbc.Driver"); 
            con= DriverManager.getConnection("jdbc:mysql://localhost/bussystem","root","");
          //pst=con.prepareStatement("select seats.busno,seats.seats,seats.status,seats.date,busbook.customer,busbook.source,busbook.destination,busbook.mobile from seats left JOIN busbook ON seats.busno=busbook.busno AND seats.seats=busbook.seat AND seats.date=busbook.date");
          //pst=con.prepareStatement("select* seats from busbook where seats.busno=busbook.busno AND seats.seats=busbook.seat AND seats.date=busbook.date");
           // pst=con.prepareStatement("select * from seats, busbook");
          // pst.setString(1,date);
            pst=con.prepareStatement("select*from busbook");
               rs =pst.executeQuery();
            
            //pst.executeUpdate();
            ResultSetMetaData rsd=rs.getMetaData();
            int c;
            c=rsd.getColumnCount();
            DefaultTableModel d= (DefaultTableModel)Table1.getModel();
           d.setRowCount(0);
            
            
            while(rs.next())
            {
                Vector v2=new Vector();
                for(int i=1;i<=c;i++)
                {
                    v2.add(rs.getString("id"));
                    //v2.add(rs.getString("busno"));
                    //v2.add(rs.getString("id"));
                    v2.add(rs.getString("customer"));
                    v2.add(rs.getString("source"));
                    v2.add(rs.getString("destination"));
                    v2.add(rs.getString("mobile"));
                    v2.add(rs.getString("date"));
                    v2.add(rs.getString("time"));
                    v2.add(rs.getString("status"));
                    
                    
                }
                d.addRow(v2);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ShowT.class.getName()).log(Level.SEVERE, null, ex);
        }
            
       
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       load();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtmnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmnoActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)Table1.getModel();
        int selectedIndex = Table1.getSelectedRow();
        
        txtcustname.setText(Df.getValueAt(selectedIndex, 1).toString());
        //txtbusno.setSelectedItem(Df.getValueAt(selectedIndex, 1).toString());
        txtsource.setSelectedItem(Df.getValueAt(selectedIndex, 2).toString());
        txtdestin.setSelectedItem(Df.getValueAt(selectedIndex, 3).toString());
        txtmno.setText(Df.getValueAt(selectedIndex, 4).toString());
        txtdate.setText(Df.getValueAt(selectedIndex, 5).toString());
        txttime.setSelectedItem(Df.getValueAt(selectedIndex, 6).toString());
        
       
    }//GEN-LAST:event_Table1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
       // for(int i=1;i<=28;i++)
        {    
            try {
            
                
            // TODO add your handling code here:
           load();
            
       // String date =txtdate.getDate().toString();
            String cusname=txtcustname.getText();
            //String seat=txtsno.getText();
            //String busno=txtbusno.getSelectedItem().toString();
            String source=txtsource.getSelectedItem().toString();
            String destination=txtdestin.getSelectedItem().toString();
            String mno=txtmno.getText();
            String date=txtdate.getText();
            String time= txttime.getSelectedItem().toString();
            
           
            //String busno=txtsno.getText();
            
            //int seatno=i;
              
            String status=" booked";
            
            pst=con.prepareStatement("insert into busbook(customer,source,destination,mobile,date,time,status)values(?,?,?,?,?,?,?)");
             //pst.setString(1,busno);
            //pst.setInt(2,seatno);
            pst.setString(1,cusname);
            pst.setString(2,source);
            pst.setString(3,destination);
            pst.setString(4,mno);
            pst.setString(5,date);
            pst.setString(6,time);
            pst.setString(7,status);
            
            pst.executeUpdate();
           // load();
            
            
            //pst1=con.prepareStatement("update busbuk ");
            //pst1.setString(1,"booked");
            
           // pst1.setString(2,seat);
           
           // pst1.executeUpdate();
            //load();
            
            
            JOptionPane.showMessageDialog(this,"busbooked");
              load();
            txtcustname.setText(" ");
            //txtsno.setText(" ");
            txtsource.setSelectedItem(" ");
            txtdestin.setSelectedItem(" ");
            txtmno.setText(" ");
            //txtdate.setText(" ");
            //txttime.setSelectedItem(" ");
           //txtdate.setSelectedItem(" ");
            
           // txtcustname.requestFocus();
            
            
            
            
            
            
            
             
            
        } catch (SQLException ex) {
            Logger.getLogger(ShowT.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        otheradmin n=new otheradmin();
        n.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    System.exit(0);
        
                
    
    

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
             DefaultTableModel Df = (DefaultTableModel)Table1.getModel();
        int selectedIndex = Table1.getSelectedRow();
        try {
            int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            
                       String CustomerName=txtcustname.getText();
                        
                       String Source=txtsource.getSelectedItem().toString();
                       String Destination=txtdestin.getSelectedItem().toString();
                       String Mobile=txtmno.getText();
                       String date =txtdate.getText();
                       String Time=txttime.getSelectedItem().toString();
  
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/bussystem","root","");
            pst= con.prepareStatement("update busbook set customer=?,source=?,destination=?,mobile = ?,date=?,time=? where id=?");
            pst.setString(1, CustomerName);
            pst.setString(2, Source);
            pst.setString(3, Destination);
            pst.setString(4, Mobile);
            pst.setString(5,date);
            pst.setString(6,Time);
  
            pst.setInt(7,id);
           
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Booking updated");
                 load();
             
                txtcustname.setText("");
                txtsource.setSelectedItem("");
                txtdestin.setSelectedItem("");
                //txtbusno.setSelectedItem("");
                
               // txtdate.getDate();
               txtdate.setText("");
                txtmno.setText("");
                txttime.setSelectedItem("");
                txtcustname.requestFocus();
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(ShowT.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      catch (SQLException ex) {
            Logger.getLogger(ShowT.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
DefaultTableModel Df = (DefaultTableModel)Table1.getModel();
        int selectedIndex = Table1.getSelectedRow();
        try {
            int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            int dialogResult = JOptionPane.showConfirmDialog(null," Do you want to delete the booking?","warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_NO_OPTION)
            {
                Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/bussystem","root","");
            pst = con.prepareStatement("delete from busbook where id=?");
             
            pst.setInt(1,id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Booking Deleted");
                 load();
             
                txtcustname.setText("");
         
                txtsource.setSelectedItem("");
                txtdestin.setSelectedItem("");
                //txtbusno.setSelectedItem("");
                txtmno.setText("");
                //txtdate.setText();
                txttime.setSelectedItem("");

                txtcustname.requestFocus();   
            }
 
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(ShowT.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      catch (SQLException ex) {
            Logger.getLogger(ShowT.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser txtchooser;
    private javax.swing.JTextField txtcustname;
    private javax.swing.JTextField txtdate;
    private javax.swing.JComboBox<String> txtdestin;
    private javax.swing.JTextField txtmno;
    private javax.swing.JComboBox<String> txtsource;
    private javax.swing.JComboBox<String> txttime;
    // End of variables declaration//GEN-END:variables
}
